<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>AccessDemo2.Five</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessDemo1\AccessDemo1.csproj" />
  </ItemGroup>

</Project>
